steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/emotion-ai:$BUILD_ID'
    - '-t'
    - 'gcr.io/$PROJECT_ID/emotion-ai:latest'
    - '.'
  timeout: 1200s

# Push the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/emotion-ai:$BUILD_ID']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/emotion-ai:latest']

# Run basic tests (optional - uncomment if you have tests)
# - name: 'gcr.io/cloud-builders/docker'
#   entrypoint: 'sh'
#   args:
#     - '-c'
#     - |
#       docker run --rm \
#         -e GOOGLE_API_KEY="dummy-key-for-testing" \
#         gcr.io/$PROJECT_ID/emotion-ai:$COMMIT_SHA \
#         python -m pytest tests/ -v
#   timeout: 300s

# Deploy to Cloud Run with enhanced configuration
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/emotion-ai:$BUILD_ID'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '8Gi'
      - '--cpu'
      - '2'
      - '--concurrency'
      - '10'
      - '--max-instances'
      - '5'
      - '--min-instances'
      - '1'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'FLASK_ENV=production'
      - '--set-env-vars'
      - 'EMOTION_CONFIDENCE_THRESHOLD=0.7'
      - '--set-env-vars'
      - 'MAX_IMAGE_SIZE=2097152'
      - '--port'
      - '8080'
      - '--set-secrets=GOOGLE_API_KEY=GOOGLE_API_KEY:latest'
  timeout: 600s

# Blue-green deployment strategy (optional)
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args:
#     - 'run'
#     - 'deploy'
#     - 'emotion-ai-candidate'
#     - '--image'
#     - 'gcr.io/$PROJECT_ID/emotion-ai:$COMMIT_SHA'
#     - '--region'
#     - 'us-central1'
#     - '--platform'
#     - 'managed'
#     - '--allow-unauthenticated'
#     - '--no-traffic'
#     - '--tag'
#     - 'candidate'
#   timeout: 600s

# Update traffic to new version (uncomment for blue-green deployment)
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args:
#     - 'run'
#     - 'services'
#     - 'update-traffic'
#     - 'emotion-ai'
#     - '--to-revisions'
#     - 'candidate=100'
#     - '--region'
#     - 'us-central1'

# Store build information
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      echo "Build completed successfully!" > build_info.txt
      echo "Commit SHA: $COMMIT_SHA" >> build_info.txt
      echo "Build ID: $BUILD_ID" >> build_info.txt
      echo "Timestamp: $(date)" >> build_info.txt
      gsutil cp build_info.txt gs://$PROJECT_ID-build-logs/builds/$BUILD_ID/

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/emotion-ai:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/emotion-ai:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 50
  logging: CLOUD_LOGGING_ONLY
  logStreamingOption: STREAM_ON
  env:
    - 'DOCKER_BUILDKIT=1'

# Timeout for entire build
timeout: 2400s

# Substitutions for dynamic values
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'emotion-ai'

# Tags for build tracking
tags:
  - 'emotion-ai'
  - 'cloud-run'
  - 'ml-service'